Repository ohDelivery/OhDelivery, pull requests merged in 2025-04, with the labels that each got.

#10 feature : 매칭 서비스 모듈 생성
  match-service/.gitattributes
  match-service/.gitignore
  match-service/build.gradle
  match-service/gradle/wrapper/gradle-wrapper.jar
  match-service/gradle/wrapper/gradle-wrapper.properties
  match-service/gradlew
  match-service/gradlew.bat
  match-service/settings.gradle
  match-service/src/main/java/com/ohdelivery/service/match/MatchServiceApplication.java
  match-service/src/main/resources/application.yml
  match-service/src/test/java/com/ohdelivery/service/match/MatchServiceApplicationTests.java
Labels: enhancement

#14 chore: add docker-compose.yml
  docker-compose.yml
  postgres/init.sql
Labels: enhancement

#15 매칭 CRUD 작성
  common/src/main/java/com/ohdelivery/common/CommonApplication.java
  common/src/main/java/com/ohdelivery/common/model/JpaConfig.java
  match-service/build.gradle
  match-service/docker-compose.yml
  match-service/settings.gradle
  match-service/src/main/java/com/ohdelivery/service/match/MatchServiceApplication.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/CreateMatchingRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/UpdateMatchingRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/response/GetMatchingResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/Matching.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/repository/MatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/DeliveryInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/PayInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/RiderInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/JpaMatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/MatchingRepositoryImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/resources/application.yml
  settings.gradle
Labels: enhancement

#17 [Feat] 공통 모듈 AuditorAwareImpl
  common/src/main/java/com/ohdelivery/common/CommonApplication.java
  common/src/main/java/com/ohdelivery/common/config/JpaConfig.java
  common/src/main/java/com/ohdelivery/common/model/AuditorAwareImpl.java
  common/src/main/java/com/ohdelivery/common/model/JpaConfig.java
  common/src/main/resources/application.yml
Labels: enhancement

#18 rider CRUD 기능 구현
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/response/GetMatchingResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/request/CreateRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/request/UpdateRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/response/GetRiderResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/model/Rider.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/model/RiderStatus.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/repository/RiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/JpaRiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/RiderRepositoryImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: enhancement

#25 게이트웨이 routing 구현
  api-gateway/build.gradle
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/AuthServerClient.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/GatewayConfiguration.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/WebClientConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/AuthenticationFilter.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/LoggingFilter.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/TokenFilter.java
  api-gateway/src/main/resources/application.yml
Labels: enhancement

#27 팀 규칙 적용
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/exception/MatchingExceptionHandler.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/exception/MatchingInvalidStatusException.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/exception/MatchingNotFoundException.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/request/CreateRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/request/UpdateRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/response/GetRiderResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/exception/RiderExceptionHandler.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/exception/RiderInvalidStatusException.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/exception/RiderNotFoundException.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/model/Rider.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: enhancement

#34 chore: consult-service 구성
  consult-service/build.gradle
  consult-service/gradle/wrapper/gradle-wrapper.jar
  consult-service/gradle/wrapper/gradle-wrapper.properties
  consult-service/src/main/java/com/ohdelivery/service/consult/ConsultServiceApplication.java
  consult-service/src/main/resources/application.yml
  consult-service/src/test/java/com/ohdelivery/service/consult/ConsultServiceApplicationTests.java
  settings.gradle
Labels: enhancement

#28 feat: 회원 가입, 삭제, 로그인, 조회 구현
  common/src/main/java/com/ohdelivery/common/exception/ErrorCode.java
  config-server/build.gradle
  user-service/src/main/java/com/ohdelivery/service/user/UserServiceApplication.java
  user-service/src/main/java/com/ohdelivery/service/user/application/UserService.java
  user-service/src/main/java/com/ohdelivery/service/user/application/command/CreateUserCommand.java
  user-service/src/main/java/com/ohdelivery/service/user/application/command/UserLoginCommand.java
  user-service/src/main/java/com/ohdelivery/service/user/application/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/ohdelivery/service/user/application/exception/UserException.java
  user-service/src/main/java/com/ohdelivery/service/user/domain/model/User.java
  user-service/src/main/java/com/ohdelivery/service/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/ohdelivery/service/user/infrastructure/persistence/UserJpaRepository.java
  user-service/src/main/java/com/ohdelivery/service/user/infrastructure/persistence/UserRepositoryImpl.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/controller/UserController.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/request/CreateUserRequest.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/request/UserLoginRequest.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/response/UserAuthResponse.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/response/UserLoginResponse.java
Labels: enhancement

#29 feat: 알림 기능 구현
  docker-compose.yml
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/dto/AlarmEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/dto/SlackResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/exception/AlarmErrorCode.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/exception/AlarmException.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/exception/AlarmExceptionHandler.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/service/AlarmService.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/service/SlackService.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/model/Alarm.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/model/AlarmRider.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/repository/AlarmRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/repository/AlarmRiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/config/RabbitMQConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/persistence/JpaAlarmRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/persistence/JpaAlarmRiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/presetation/AlarmController.java
  match-service/src/main/resources/application.yml
Labels: enhancement

#40 feat: 상담원 CRUD
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/dto/request/CreateAgentRequest.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/dto/request/UpdateAgentRequest.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/dto/response/AgentResponse.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/exception/AgentErrorCode.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/exception/AgentException.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/exception/AgentExceptionHandler.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/service/AgentService.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/domain/model/Agent.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/domain/model/AgentStatus.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/domain/repository/AgentRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/presentation/AgentController.java
Labels: enhancement

#46 매칭에 카프카 적용
  common/src/main/java/com/ohdelivery/common/kafka/dto/CompleteMatchingEvent.java
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingEventPublisher.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/KafkaConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchingEventProducer.java
  match-service/src/main/resources/application.yml
Labels: enhancement

#49 rider kafka 설정
  common/src/main/java/com/ohdelivery/common/kafka/Topic.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/DeleteUserEvent.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/UpdateSlackIdEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchKafkaConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/model/Rider.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/repository/RiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/messaging/KafkaUserEventConsumer.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/messaging/RiderKafkaConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/JpaRiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/RiderRepositoryImpl.java
Labels: enhancement

#54 매칭 상세 기능 구현
  common/src/main/java/com/ohdelivery/common/feign/GetDeliveryResponse.java
  common/src/main/java/com/ohdelivery/common/kafka/Topic.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/CreateMatchingEvent.java
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/MatchServiceApplication.java
  match-service/src/main/java/com/ohdelivery/service/match/common/DeliveryClientService.java
  match-service/src/main/java/com/ohdelivery/service/match/common/redisson/RedissonConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingEventPublisher.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/AssignRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/CreateMatchingRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/UpdateMatchingRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/response/GetMatchingResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/Matching.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/repository/MatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/DeliveryInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/PayInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/vo/RiderInfo.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchingEventProducer.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/JpaMatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/MatchingRepositoryImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/messaging/RiderKafkaConfig.java
Labels: enhancement

#55 Refactor: 알림 메시지큐 변경 (RabbitMQ -> Kafka)
  docker-compose.yml
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/dto/AlarmCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/dto/AlarmEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/service/AlarmService.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/model/Alarm.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/domain/model/AlarmRider.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/config/AlarmKafkaConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/config/RabbitMQConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/messaging/AlarmEventConsumer.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/presetation/AlarmController.java
Labels: enhancement

#58 fix : redisson 비밀번호 추가
  match-service/src/main/java/com/ohdelivery/service/match/common/redisson/RedissonConfig.java
Labels: bug

#63 fix pr누락된거 수정
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingEventPublisher.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchingEventProducer.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
Labels: bug

#56 feat: 배달 중 라이더 실시간 위치 추적
  api-gateway/build.gradle
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/GatewayConfiguration.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/TomcatConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  api-gateway/src/main/resources/application.yml
  common/src/main/java/com/ohdelivery/common/kafka/dto/CreateDeliveryEvent.java
  delivery-service/build.gradle
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/request/RiderLocationRequest.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/response/DeliveryRecordResponse.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/response/DeliveryResponse.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/response/RiderLocationResponse.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/exception/DeliveryExceptionHandler.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/WebSocketEventService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/WebSocketEventServiceImpl.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/dto/RiderLocation.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/service/RiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/config/RedisConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/config/WebSocketConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/exception/RiderLocationNotFoundException.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/messaging/JwtHandshakeInterceptor.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/messaging/MatchingEventConsumer.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/service/RedisRiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/ConsumerWebSocketHandler.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/RiderWebSocketHandler.java
  delivery-service/src/main/resources/client/consumer-websocket-client.html
  delivery-service/src/main/resources/client/rider-websocket-client.html
Labels: enhancement

#66 Delivery 컨슈머 추가
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/CreateDeliveryEvent.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/CreateMatchingEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/CreateMatchingRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/KafkaDeliveryEventConsumer.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchKafkaConfig.java
Labels: enhancement

#68 refactor : 연동위한 수정
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  common/src/main/java/com/ohdelivery/common/feign/GetDeliveryResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/common/DeliveryClientService.java
Labels: enhancement

#67 Feature/gateway 59 cors csrf
  api-gateway/build.gradle
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/CorsConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/GatewayConfiguration.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/GatewayConstants.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/AuthenticationFilter.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/CsrfFilter.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/filter/TokenFilter.java
  api-gateway/src/main/resources/application.yml
  auth-server/src/main/java/com/ohdelivery/server/authserver/application/jwt/JwtProvider.java
Labels: enhancement

#75 feat: delivery controller role check
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/controller/DeliveryController.java
Labels: feat

#74 feat: 인센티브 role check 추가
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/out/KafkaProducer.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/presentation/IncentiveController.java
  incentive-service/src/main/resources/application.yml
Labels: feat

#80 매칭,라이더 롤 체크 어노테이션 적용
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/AssignRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/KafkaDeliveryEventConsumer.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: enhancement

#79 feat: 상담원 매칭 role check 추가
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  consult-service/src/main/java/com/ohdelivery/service/consult/ConsultServiceApplication.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/exception/AgentErrorCode.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/application/service/AgentService.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/domain/repository/AgentRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/presentation/AgentController.java
  consult-service/src/main/resources/application.yml
Labels: feat

#82 Feature/auth 78 user auditing aware
  common/src/main/java/com/ohdelivery/common/annotations/CurrentUser.java
  common/src/main/java/com/ohdelivery/common/config/UserContextConfig.java
  common/src/main/java/com/ohdelivery/common/model/AuditorAwareImpl.java
  common/src/main/java/com/ohdelivery/common/passport/Passport.java
  common/src/main/java/com/ohdelivery/common/passport/usercontext/PassportArgumentResolver.java
  common/src/main/java/com/ohdelivery/common/passport/usercontext/UserContextFilter.java
  common/src/main/java/com/ohdelivery/common/passport/usercontext/UserContextHolder.java
Labels: enhancement

#83 feature : 매칭 생성 실패 보상 트랜잭션 구현
  common/src/main/java/com/ohdelivery/common/kafka/Topic.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/FailCreateMatchingEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingEventPublisher.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchingEventProducer.java
Labels: enhancement

#88 [Feat] 매칭 실패 보상 트랜잭션 컨슈머 구현
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/model/Delivery.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/model/DeliveryStatus.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/config/KafkaConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/messaging/MatchingEventConsumer.java
Labels: enhancement

#86 롤에 따른 상세 로직 추가
  common/src/main/java/com/ohdelivery/common/kafka/dto/DeleteUserEvent.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/UpdateSlackIdEvent.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/request/AssignRiderRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/dto/response/SearchMatchingResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/repository/MatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/JpaMatchingRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/persistence/MatchingRepositoryImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/response/GetRiderResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/response/UpdateRiderStatusResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/model/Rider.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/domain/repository/RiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/JpaRiderRepository.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/infrastructure/persistence/RiderRepositoryImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
  user-service/src/main/java/com/ohdelivery/service/user/infrastructure/messaging/UserEventProducer.java
Labels: enhancement

#93 feat: 웹소켓 알림 전송 기능 구현
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/GatewayConfiguration.java
  common/src/main/java/com/ohdelivery/common/kafka/dto/CreateMatchingEvent.java
  match-service/build.gradle
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/dto/AlarmRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/service/AlarmService.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/websocket/CustomHandshakeHandler.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/websocket/CustomHandshakeInterceptor.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/application/websocket/StompPrincipal.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/config/WebClientConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/config/WebSocketConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/alarm/infrastructure/messaging/AlarmEventConsumer.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/MatchingEventPublisher.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchingEventProducer.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/resources/static/alarm-websocket-client.html
Labels: enhancement

#94 Refactor: 상담원 매칭 리팩토링
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/domain/repository/AgentRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/agent/infrastructure/JpaAgentRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/application/service/AgentMatchingService.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/domain/repository/AgentMatchingRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/domain/repository/RedisAgentRepository.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/domain/strategy/AgentMatchingStrategy.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/domain/strategy/LeastBusyStrategy.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/domain/strategy/RoundRobinStrategy.java
  consult-service/src/main/java/com/ohdelivery/service/consult/matching/infrastructure/JpaAgentMatchingRepository.java
Labels: refactor

#96 Refactor: DLQ+재시도 로직 추가 및 디자인 패턴 리팩토링
  common/src/main/java/com/ohdelivery/common/model/AuditorAwareImpl.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/DailyDistancePolicy.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/DailyIncentiveTransformer.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/IncentivePolicy.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/IncentiveService.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/PerTimePolicy.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/config/KafkaConfig.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/dto/DlqMessage.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/in/DlqConsumer.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/in/IncentiveStreamProcessor.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/out/DlqProducer.java
Labels: refactor

#97 Refactor: 딜리버리 서비스 옵저버 패턴 리팩토링
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/CorsConfig.java
  common/src/main/java/com/ohdelivery/common/model/AuditorAwareImpl.java
  common/src/main/java/com/ohdelivery/common/passport/RoleType.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/request/RiderLocationRequest.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/observer/BroadcasterManager.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/observer/LocationBroadcaster.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/observer/Observer.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/observer/Subject.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/DeliveryServiceImpl.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/WebSocketEventService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/WebSocketEventServiceImpl.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/service/RiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/config/RedisConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/config/WebSocketConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/observer/WebSocketLocationObserver.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/security/JwtHandshakeInterceptor.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/service/RedisRiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/ConsumerWebSocketHandler.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/RiderWebSocketHandler.java
Labels: refactor

#104 [Feat] Redis geo 만료 로직
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/request/RiderLocationRequest.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/response/RiderLocationResponse.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/LocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/domain/service/RiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/redis/RedisConfig.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/redis/RedisGeoEventHandler.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/redis/RedisGeoExpiredEvent.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/redis/RedisKey.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/redis/RedisKeyExpiredListener.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/infrastructure/service/RedisRiderLocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/RiderWebSocketHandler.java
  docker-compose.yml
Labels: enhancement

#98 커맨드 디자인 패턴 적용
  common/src/main/java/com/ohdelivery/common/feign/request/ClientGetNearRidersRequest.java
  common/src/main/java/com/ohdelivery/common/feign/response/ClientGetRiderResponse.java
  match-service/src/main/java/com/ohdelivery/service/match/common/command/CommandFactory.java
  match-service/src/main/java/com/ohdelivery/service/match/common/command/CommandInvoker.java
  match-service/src/main/java/com/ohdelivery/service/match/common/command/MatchingCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/common/feign/DeliveryClientService.java
  match-service/src/main/java/com/ohdelivery/service/match/common/feign/RiderClientService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/command/CreateMatchingCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/command/DeleteMatchingCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/command/MatchingCommandFactory.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/command/UpdateMatchingCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/exception/MatchingCreateException.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/exception/MatchingUpdateException.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingDeleteException.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/domain/Matching.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/config/SagaConfig.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/dto/request/GetNearRidersRequest.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderService.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/application/service/RiderServiceImpl.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: enhancement

#103 게이트웨이 팩토리 패턴 리팩토링
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/FilterConfiguration.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/config/GatewayConfiguration.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/constants/ServiceConstants.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/DefaultRouteFactory.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/RouteFactory.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/RouteFactoryRegistry.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/config/GatewayServiceProperties.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/model/DefaultRouteConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/model/DefaultServiceConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/model/RouteConfig.java
  api-gateway/src/main/java/com/ohdelivery/gateway/apigateway/routes/model/ServiceConfig.java
  api-gateway/src/main/resources/application.yml
  auth-server/build.gradle
  common/src/main/java/com/ohdelivery/common/model/AuditorAwareImpl.java
  common/src/main/java/com/ohdelivery/common/passport/usercontext/UserContextHolder.java
  user-service/build.gradle
  user-service/src/main/java/com/ohdelivery/service/user/application/UserService.java
  user-service/src/main/java/com/ohdelivery/service/user/application/command/UpdateSlackIdCommand.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/controller/UserController.java
  user-service/src/main/java/com/ohdelivery/service/user/presentation/request/UpdateSlackIdRequest.java
Labels: refactor

#105 Refactor: DLQ 로직 수정 + Grafana Slack 에러 이벤트 알림
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/DailyIncentiveTransformer.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/application/service/PerTimePolicy.java
  incentive-service/src/main/java/com/ohdelivery/service/incentive/infrastructure/messaging/in/DlqConsumer.java
Labels: refactor

#108 커맨드 패턴 테스트 코드 작성
  match-service/src/main/java/com/ohdelivery/service/match/common/command/CommandInvoker.java
  match-service/src/test/java/com/ohdelivery/service/match/matching/application/service/CommandPatternTest.java
  match-service/src/test/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImplTest.java
Labels: enhancement

#112 매칭에 스웨거 적용
  match-service/src/main/java/com/ohdelivery/service/match/matching/presentation/MatchingController.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: enhancement

#115 fix : 페인 주변 라이더 조회 기능 수정
  match-service/src/main/java/com/ohdelivery/service/match/common/feign/RiderClientService.java
  match-service/src/main/java/com/ohdelivery/service/match/matching/application/command/CreateMatchingCommand.java
  match-service/src/main/java/com/ohdelivery/service/match/rider/presentation/RiderController.java
Labels: bug

#117 [Feat] 딜리버리 모니터링 & 성능 테스트
  delivery-service/build.gradle
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/dto/request/RiderLocationRequest.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/application/service/LocationService.java
  delivery-service/src/main/java/com/ohdelivery/service/delivery/presentation/handler/RiderWebSocketHandler.java
  delivery-service/src/main/resources/client/rider-websocket-client.html
  delivery-service/src/main/resources/test/k6-rider-loadtest.js
  delivery-service/src/main/resources/test/k6-rider-login-connection-send-test.js
  delivery-service/src/main/resources/test/k6-rider-signup.js
  prometheus/prometheus.yml
Labels: enhancement

#120 Fix: 매칭 생성 실패 이벤트 deserialize 에러 픽스
  api-gateway/src/main/resources/application.yml
  common/src/main/java/com/ohdelivery/common/kafka/dto/FailCreateMatchingEvent.java
Labels: bug

#118 매칭 dlq 구현
  match-service/src/main/java/com/ohdelivery/service/match/matching/infrastructure/messaging/MatchKafkaConfig.java
  match-service/src/test/java/com/ohdelivery/service/match/matching/application/service/CommandPatternTest.java
  match-service/src/test/java/com/ohdelivery/service/match/matching/application/service/MatchingServiceImplTest.java
Labels: enhancement
